spring.application.name=sistema-logistica

# Datos de la base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/logitrack_db
#El usuario por defecto es postgres, mas adelante lo podemos cambiar
spring.datasource.username=postgres
#La contraseña fue creada en pgAdmin4
spring.datasource.password=1234

# Hibernate para que cree las tablas solo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=logitrack-clave-secreta

#para swagger 
spring.jackson.property-naming-strategy=SNAKE_CASE


